<a href="https://colab.research.google.com/github/laxmiprasanna8741/pytorch-practice/blob/main/simple_neuralnetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import pandas as pd
import torch.nn.functional as F
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split


In [ ]:
class Model(nn.Module):
  def __init__(self,in_features=4,h1=8,h2=9,out_features=3):
    super().__init__()
    self.layer1 = nn.Linear(in_features,h1)
    self.layer2 = nn.Linear(h1,h2)
    self.out = nn.Linear(h2,out_features)

  def forward(self,x):
    x = F.relu(self.layer1(x))
    x = F.relu(self.layer2(x))
    out = self.out(x)

    return out

In [ ]:
torch.manual_seed(41)
model = Model()

In [ ]:
print(model)

Model(
  (layer1): Linear(in_features=4, out_features=8, bias=True)
  (layer2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)


In [ ]:
df = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")
df.sample(5)

sepal.length  sepal.width  petal.length  petal.width     variety
138           6.0          3.0           4.8          1.8   Virginica
9             4.9          3.1           1.5          0.1      Setosa
78            6.0          2.9           4.5          1.5  Versicolor
130           7.4          2.8           6.1          1.9   Virginica
135           7.7          3.0           6.1          2.3   Virginica

In [ ]:
df.shape

(150, 5)

In [ ]:
encoder = LabelEncoder()
df["variety"] = encoder.fit_transform(df["variety"])


In [ ]:
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety           int64
dtype: object

In [ ]:
encoder.classes_


array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [ ]:
df.head(5)

sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
X = df.drop("variety",axis = 1).values
y = df["variety"].values

In [ ]:
y[:5]

array([0, 0, 0, 0, 0])

In [ ]:
X_train ,X_test ,y_train ,y_test = train_test_split(X,y,test_size = 0.2,random_state = 32)


In [ ]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test )
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr = 0.01)

In [ ]:
epochs = 100
losses = []

for i in range(epochs):
  y_pred = model.forward(X_train)
  loss = criterion(y_pred,y_train)
  losses.append(loss)

  if i%10 == 0:
    print(f"epochs {i} loss is {loss}")

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()




epochs 0 loss is 0.0721406564116478
epochs 10 loss is 0.08194348961114883
epochs 20 loss is 0.06954659521579742
epochs 30 loss is 0.06309784203767776
epochs 40 loss is 0.060757026076316833
epochs 50 loss is 0.05903780087828636
epochs 60 loss is 0.05755119025707245
epochs 70 loss is 0.056636709719896317
epochs 80 loss is 0.05591445788741112
epochs 90 loss is 0.05535821616649628


In [ ]:
with torch.no_grad():
  y_eval = model.forward(X_test)
  loss = criterion(y_eval,y_test)

print(f"the loss is {loss}")


the loss is 0.03152170404791832


In [ ]:
correct = 0

with torch.no_grad():
  for i , data in enumerate(X_test):
    y_eval = model.forward(data)

    print(f"{i+1} ,{str(y_eval)} ,{y_test[i]}, {y_eval.argmax().item()}")

    if y_eval.argmax().item() == y_test[i]:
      correct += 1

print(f"the accuracy is {correct/len(y_test)}")

1 ,tensor([-6.7748,  6.1458,  1.6827]) ,1, 1
2 ,tensor([ 12.2036,  -3.9679, -10.1808]) ,0, 0
3 ,tensor([ 8.5980, -1.5465, -8.2602]) ,0, 0
4 ,tensor([-7.4942,  6.8390,  1.7389]) ,1, 1
5 ,tensor([-11.5503,   3.8263,   8.1498]) ,2, 2
6 ,tensor([-13.5111,   5.7497,   8.2866]) ,2, 2
7 ,tensor([ 7.4811, -0.8022, -7.6632]) ,0, 0
8 ,tensor([ 9.3469, -2.0960, -8.6005]) ,0, 0
9 ,tensor([-6.7770,  6.8667,  1.0520]) ,1, 1
10 ,tensor([ 9.7450, -2.2161, -8.9963]) ,0, 0
11 ,tensor([-7.4881,  7.3421,  1.2843]) ,1, 1
12 ,tensor([-13.6906,   3.7398,  10.1607]) ,2, 2
13 ,tensor([-4.1814,  6.1789, -0.7500]) ,1, 1
14 ,tensor([-4.4897,  6.7564, -0.9494]) ,1, 1
15 ,tensor([-12.0539,   4.6223,   7.8797]) ,2, 2
16 ,tensor([-13.1395,   2.7877,  10.4784]) ,2, 2
17 ,tensor([-7.4929,  5.7459,  2.6937]) ,1, 1
18 ,tensor([-10.7000,   4.9858,   6.3034]) ,2, 2
19 ,tensor([-4.6621,  6.7246, -0.7726]) ,1, 1
20 ,tensor([11.0870, -2.9830, -9.8775]) ,0, 0
21 ,tensor([ 8.4762, -1.4109, -8.2442]) ,0, 0
22 ,tensor([-14.6227, 

In [ ]:
new_iris = torch.tensor([4.7,3.2,1.3,0.2])

In [ ]:
with torch.no_grad():
  print(model(new_iris))

tensor([10.2018, -2.6972, -9.0226])


In [ ]:
new_iris = torch.tensor([5.9,3.0,5.1,1.8])

In [ ]:
with torch.no_grad():
  print(model(new_iris))

tensor([-11.1125,   4.1866,   7.4063])


In [ ]:
torch.save(model.state_dict(),"iris_model_v1.pt")

In [ ]:
new_model = Model()
new_model.load_state_dict(torch.load("iris_model_v1.pt"))

<All keys matched successfully>

In [ ]:
new_model.eval()

Model(
  (layer1): Linear(in_features=4, out_features=8, bias=True)
  (layer2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)