<a href="https://colab.research.google.com/github/laxmiprasanna8741/pytorch-practice/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<h2>Tensors</h2>


*   A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar to numpy array but full of fun things that make them work better on GPU's(vs Regular CPU's)

*  default data type of float32 .
*  More suitable for deep learning than a numpy array.







In [ ]:
import torch
import numpy as np

<h3>LISTS</h3>

In [ ]:
int_list = [[1,2,3,4,5],[4,5,6,7,8]]
int_list

[[1, 2, 3, 4, 5], [4, 5, 6, 7, 8]]

<h3>Numpy Array</h3>

In [ ]:
arr = np.random.rand(3,4)
arr

array([[0.7246933 , 0.73991155, 0.3297039 , 0.14989364],
       [0.72949113, 0.63328779, 0.47712372, 0.2917504 ],
       [0.73078682, 0.15291791, 0.42743526, 0.46903091]])

In [ ]:
arr.dtype

dtype('float64')

<h3>TENSOR</h3>

In [ ]:
tensor_arr = torch.randn(3,4)
tensor_arr

tensor([[ 0.8313,  1.9062, -1.2253, -0.2664],
        [ 0.1866, -0.3755, -0.6233, -0.6164],
        [ 1.0678, -1.2497, -0.4754,  0.4724]])

In [ ]:
tensor_arr.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#creating tensor from a numpy array

my_tensor = torch.tensor(arr ,dtype = torch.float32)
my_tensor

tensor([[0.7247, 0.7399, 0.3297, 0.1499],
        [0.7295, 0.6333, 0.4771, 0.2918],
        [0.7308, 0.1529, 0.4274, 0.4690]])

<h1>Tensor_operation</h1>




In [ ]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_tensor1 = torch.arange(10)
my_tensor1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_tensor1 = my_tensor1.reshape(2,-1)
my_tensor1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_tensor1 = my_tensor1.reshape(-1,5)
my_tensor1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_tensor2 = torch.arange(10)
my_tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_tensor2 = my_tensor2.view(2,5)
my_tensor2


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
a = torch.arange(10).reshape(2, 5)
a

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
a.stride()


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
a.view(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
a.view(5,2).stride()

(2, 1)

In [ ]:
a.t()

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

In [ ]:
a.t().stride()

(1, 5)

In [ ]:
a.t()

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

In [ ]:
a = torch.arange(8).reshape(2,4)
a

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [ ]:
a.t()

tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])

In [ ]:
a.t().view(2,2,2)

tensor([[[0, 4],
         [1, 5]],

        [[2, 6],
         [3, 7]]])

In [ ]:
my_torch8 = torch.arange(10)
my_torch8

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch8[0:5:1]

tensor([0, 1, 2, 3, 4])

In [ ]:
my_torch8 = my_torch8.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[2:4,0:1]

tensor([[4],
        [6]])

<h2>TENSOR MATH OPERATION </h2>

In [2]:
import torch

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [5]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [10]:
torch.sub(tensor_a,tensor_b).abs()

tensor([4, 4, 4, 4])

In [11]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [13]:
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [17]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [19]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [20]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
#reassignment_
#first way
Tensor_a = tensor_a + tensor_b

#second way
tensor_a.add_(tensor_b)

#third way
torch.add(tensor_a,tensor_b,out = tensor_a)